# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a94e4bf1e458aa3b82ea2948b3a30466c8ac69ea7c3971a43f7fa3bc5ccae221103507ac08c6d340d3bc489170c1acf58ee58063523fbfedb52976d89e6b80

test:
  secret_key_base: 5e3b302ab7237350ece540f2875dba0c4619e63038dc4d3e89cef22ce885f5e42bfe39d788ba1e9032b2e2e31ae80a4310df41ab2a93da9117a3fb33c4bbc0dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
